### ISSUE TITLE
Notes on using git branches

### ISSUE THREAD

**Issue by gstanden** [gstanden/orabuntu-lxc#123]
Working on dynamic tar of nameserver, created branch as follows:

```
orabuntu@ip-10-0-137-100:~/Downloads/orabuntu-lxc$ git checkout master
M	anylinux/anylinux-services.sh
M	orabuntu/archives/nameserver_copy.sh
M	orabuntu/orabuntu-services-1.sh
M	orabuntu/orabuntu-services-2.sh
M	orabuntu/orabuntu-services-5.sh
Already on 'master'
Your branch is up-to-date with 'origin/master'.
orabuntu@ip-10-0-137-100:~/Downloads/orabuntu-lxc$ git branch dynamic-tar
orabuntu@ip-10-0-137-100:~/Downloads/orabuntu-lxc$ git checkout dynamic-tar
M	anylinux/anylinux-services.sh
M	orabuntu/archives/nameserver_copy.sh
M	orabuntu/orabuntu-services-1.sh
M	orabuntu/orabuntu-services-2.sh
M	orabuntu/orabuntu-services-5.sh
Switched to branch 'dynamic-tar'

orabuntu@ip-10-0-137-100:~/Downloads/orabuntu-lxc$ git push origin dynamic-tar
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:gstanden/orabuntu-lxc.git
 * [new branch]      dynamic-tar -> dynamic-tar
orabuntu@ip-10-0-137-100:~/Downloads/orabuntu-lxc$
```

**Comment by kenia-borges** [comment]
orabuntu@ip-10-0-137-100:~/Downloads/orabuntu-lxc$ git checkout master
M	anylinux/anylinux-services.sh
M	orabuntu/archives/nameserver_copy.sh
M	orabuntu/orabuntu-services-1.sh
M	orabuntu/orabuntu-services-2.sh
M	orabuntu/orabuntu-services-5.sh
Already on 'master'
Your branch is up-to-date with 'origin/master'.
orabuntu@ip-10-0-137-100:~/Downloads/orabuntu-lxc$ git branch dynamic-tar
orabuntu@ip-10-0-137-100:~/Downloads/orabuntu-lxc$ git checkout dynamic-tar
M	anylinux/anylinux-services.sh
M	orabuntu/archives/nameserver_copy.sh
M	orabuntu/orabuntu-services-1.sh
M	orabuntu/orabuntu-services-2.sh
M	orabuntu/orabuntu-services-5.sh
Switched to branch 'dynamic-tar'

orabuntu@ip-10-0-137-100:~/Downloads/orabuntu-lxc$ git push origin dynamic-tar
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:gstanden/orabuntu-lxc.git
 * [new branch]      dynamic-tar -> dynamic-tar
orabuntu@ip-10-0-137-100:~/Downloads/orabuntu-lxc$

**Comment by gstanden** [comment]
Done.
