### ISSUE TITLE
Cannot access "new" documentation link - "You need Permission"

### ISSUE THREAD

**Issue by bmullan** [gstanden/orabuntu-lxc#143]
Gilbert
I tried to go to the "documention" link below but got a message that says 

> *"You Need Permission" *

> Update: May 14, 2019
> 
> Visit the new Orabuntu-LXC Documentation Site:
> 
>    https://sites.google.com/a/orabuntu-lxc.com/documentation/
![image](https://user-images.githubusercontent.com/1682855/108116863-3308ef80-706a-11eb-9bdb-f7aa01727648.png)

**Comment by gstanden** [comment]
Brian, It should be public now.  Please LMK if it is not.  Thank you for your interest.  The documentation site is next up for major expansion after I get v 7.0.0-beta AMIDE released which hopefully will be in days not weeks.  Thanks for your patience sorry for the delay getting the permissions opened up.

**Comment by bmullan** [comment]
Gilbert

I hope you are doing well.  This pandemic has interrupted everyone's life
in one way or another.

Brian

**Comment by gstanden** [comment]
Thanks Brian.  Starting to get some time in on the documentation site.  Here's a brief page that I've started that helps to explain what will be new in Orabuntu-LXC version 7.

https://sites.google.com/a/orabuntu-lxc.com/documentation/lxd
