### ISSUE TITLE
Orabuntu-LXC Lenovo P70 Mobile Workstation Giveaway 

### ISSUE THREAD

**Issue by gstanden** [gstanden/orabuntu-lxc#99]
Thanks for following Orabuntu-LXC project!  

Some github accounts do not have public email addresses.  

Please acknowledge on this ticket thread to confirm communication.  

The winner will be announced on this thread on Monday, October 16. 

The winner will need to email gilbert@orabuntu-lxc.com to claim the Lenovo P70 mobile workstation and provide shipping information.

Good luck!

Gilbert Standen, Principal Solution Architect, Orabuntu-LXC

**Comment by gstanden** [comment]
Acknowledge.

**Comment by dbaontap** [comment]
Acknowledged

**Comment by shannong** [comment]
Acknowledge

**Comment by fcolmenarez** [comment]
Acknowledge

**Comment by mrkam2** [comment]
acknowledge

**Comment by bheem123** [comment]
Acknowledged.

Thanks
Bheemsen Aitha

________________________________

**Comment by patrickho81** [comment]
Acknowledged

**Comment by dmcwhinnie** [comment]
Acknowledged.

**Comment by balaganski** [comment]
Acknowledged

**Comment by mirage22** [comment]
Acknowledge

**Comment by tassels** [comment]
Acknowledge

**Comment by ncomet** [comment]
Acknowledged

**Comment by ncomet** [comment]
Sorry, maybe I've missed something, but was a winner announced ?

**Comment by foohomesuite** [comment]
I'm not sure...

**Comment by gstanden** [comment]
Sorry everyone I am traveling on business in Copenhagen Denmark at DockerCon EU and forgot to do the drawing. I will do it now and announce winner hang on...                                                                                                                                                                        Sent from my BlackBerry - the most secure mobile device                                                                                                                                                                            From: notifications@github.comSent: October 18, 2017 20:19To: orabuntu-lxc@noreply.github.comReply-to: reply@reply.github.comCc: gilbert@orabuntu-lxc.com; author@noreply.github.comSubject: Re: [gstanden/orabuntu-lxc] Orabuntu-LXC Lenovo P70 Mobile Workstation Giveaway (#99)  I'm not sure...

**Comment by gstanden** [comment]
"fcolmenarez" you are the winner of the Lenovo P70 laptop!  Congrats!  

Please email me at gilbert@orabuntu-lxc.com with your shipping address and to verify your github identity.  You have 72 hours to respond to claim the prize or we would have to draw again.

Thanks all for participating and thanks for watching Orabuntu-LXC!  

We may have more drawings and anyone watching the project is eligible to enter.

Great new features are coming in 2017-2018 for Orabuntu-LXC so please stay tuned to the project:

1.  We are adding Docker support! side-by-side with the LXC capability.
2.  We are finalizing support for Oracle Linux 6
3.  We are adding an AWS S3 Linux container ship/archive container option
4.  We are adding Docker overlay networks for multihost as part of the Docker expansion

Note that Docker announced in Copenhagen yesterday that they now support side-by-side Swarm and Kubernetes orchestration which was huge news.

Note also that Oracle Corporation directly vends a version of Docker CE for Oracle Linux 7 even though Docker Corp itself does not FYI.

**Comment by fcolmenarez** [comment]
Will do, replying to your email.

**Comment by gstanden** [comment]
Prize awarded.
